# Generated by Django 5.1.4 on 2025-04-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000000)),
                ('isHate', models.BooleanField()),
            ],
        ),
    ]
